export const TEXT = {
    STAFF: "Nhân viên",
    REPORT: "Báo cáo",
    SETTING: "Cài đặt",
    // ACCOUNT: "Tài khoản",
    LOGIN_YOUR_ACCOUNT: "Login in to your account",
    LOGIN: "Login",
    LOGOUT: "Đăng xuất",
    USERNAME: "Username",
    ENTER_USERNAME: "Enter your username",
    // EMAIL: "Email",
    PASSWORD: "Password",
    ENTER_PASSWORD: "Enter your password",
    REMEMBER_ME: "Remember me",
    FORGOT_PASSWORD: "Forgot password ?",
    IS_REQUIRED: "không được để trống",
    ADD_NEW: "Thêm mới",
    ADD_REPORT: "Thêm báo cáo",
    ADD_STAFF: "Thêm nhân viên",
    NAME: "Tên",
    CASH: "Tiền mặt",
    TOTAL: "Tổng tiền",
    WORK_SHIFT: "Ca làm việc",
    SUBMIT_SHIFT: "Chốt ca",
    DATE: "Ngày",
    CHECK_IN: "Giờ vào",
    CHECK_OUT: "Giờ ra",
    CHECK_OUR_SMALL_THAN_CHECK_IN: "Giờ ra không được nhỏ hơn giờ vào",
    REVENUE: "Doanh thu",
    CANCEL: "Huỷ",
    SAVE: "Save",
    ENTER_SEARCH: "Nhập từ khóa tìm kiếm ...",

    IMAGE: {
        ALT: "Image",
    },
};
