export const TEXT = {
    IMAGE: {
        ALT: "Image",
    },

    STAFF: "Nhân viên",
    UPDATE_STAFF: "Cập nhật nhân viên",
    REPORT: "Báo cáo",
    LOGIN_YOUR_ACCOUNT: "Login in to your account",
    LOGIN: "Login",
    LOGOUT: "Đăng xuất",
    USERNAME: "Username",
    ENTER_USERNAME: "Enter your username",
    PASSWORD: "Password",
    ENTER_PASSWORD: "Enter your password",
    REMEMBER_ME: "Remember me",
    FORGOT_PASSWORD: "Forgot password ?",
    IS_REQUIRED: "không được để trống",
    ADD_NEW: "Thêm mới",
    ADD_REPORT: "Thêm báo cáo",
    EDIT_REPORT: "Cập nhật báo cáo",
    ADD_STAFF: "Thêm nhân viên",
    NAME: "Tên",
    CASH: "Tiền mặt",
    DEDUCTION: "Tiền khấu trừ",
    TRANSFER: "Chuyển khoản",
    TOTAL: "Tổng cộng",
    WORK_SHIFT: "Ca",
    SUBMIT_SHIFT: "Chốt ca",
    DATE: "Ngày",
    MONTH: "Tháng",
    REPORT_DATE: "Báo cáo ngày",
    ADD_DATE: "Ngày tạo",
    TIME_SHEET: "Giờ làm việc",
    TIME_NUMBER: "Số giờ",
    TIME_RANGE: "Khoảng thời gian",
    CHECK_IN: "Giờ vào",
    CHECK_OUT: "Giờ ra",
    CHECK_OUR_LARGE_THAN_CHECK_IN: "Giờ ra phải lớn hơn giờ vào",
    TOTAL_TARGET: "Tổng doanh số",
    TARGET: "Doanh số",
    TARGET_OF: "Doanh số của",
    REVENUE: "Doanh thu",
    REVENUE_GREATER_THAN_ZERO: "Doanh thu phải lớn hơn 0",
    CANCEL: "Huỷ",
    SAVE: "Save",
    ENTER_SEARCH: "Nhập từ khóa tìm kiếm ...",
    DETAIL: "Chi tiết",
    ROLE: "Vai trò",
    EDIT: "Sửa",
    DELETE: "Xoá",
    SALARY: "Tiền lương",
    SALARY_GREATER_THAN_ZERO: "Tiền lương phải lớn hơn 0",
    SALARY_OF: "Tiền lương của",
    PAYROLL_MONTH: "Bảng lương tháng",
    WORKING_DAY: "Ngày làm việc",
    PERFORMANCE: "Hiệu suất",
    SALARY_RECEIVED: "Tiền lương thực nhận",
    RANK: "Xếp hạng",
    RATE: "Tỷ lệ",
    SALARY_EACH_TIME: "Lương mỗi giờ",
    SALARY_BY_TIME: "Lương theo giờ",
    SALARY_BY_PERFORMANCE: "Lương hiệu suất",
    COPY: "Copy",
    NUMBER_IS_REQUIRED: "Chỉ được nhập số",
    NO_PERMISSION: "Bạn không có quyền truy cập",
    NOTE: "Ghi chú",
    NOTE_HAVE_DEDUCTION: "Nhập ghi chú khi có số tiền khấu trừ",
    DATE_PICKER: "Chọn ngày",
    CONFIRM_DELETE: "Bạn có chắc chắn muốn xoá ?",
    SUBMIT: "Xác nhận",
    AMOUNT: "Số tiền",
    PAID: "Đã thu tiền",
};
