import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { auth } from "@/auth";
import Provider from "@/components/Provider";
import MainLayout from "@/components/layouts";
import "./globals.scss";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await auth();

    //** Render */
    const RenderMainLayout = () => {
        if (session) {
            return <MainLayout session={session}>{children}</MainLayout>;
        }

        return children;
    };

    return (
        <html suppressHydrationWarning lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Provider>{RenderMainLayout()}</Provider>
            </body>
        </html>
    );
}
