import React from "react";
import UIProvider from "@/components/UIProvider";
import AuthProvider from "@/components/AuthProvider";
import Layouts from "@/components/layouts";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { ProfileProps } from "@/types/profileProps";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session: ProfileProps | null = await getServerSession(authOptions);

    return (
        <html suppressHydrationWarning lang="en">
            <body className={roboto.className}>
                <UIProvider>
                    <AuthProvider>
                        {session ? (
                            <Layouts session={session}>{children}</Layouts>
                        ) : (
                            children
                        )}
                    </AuthProvider>
                </UIProvider>
            </body>
        </html>
    );
}
