import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import UIProvider from "@/components/UIProvider";
import MainLayout from "@/components/layouts";
import { auth } from "@/auth";
import "./globals.scss";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await auth();

    //** Render */
    const RenderMainLayout = () => {
        if (session) {
            return <MainLayout session={session}>{children}</MainLayout>;
        }

        return children;
    };

    return (
        <html suppressHydrationWarning lang="en">
            <body className={roboto.className}>
                <UIProvider>{RenderMainLayout()}</UIProvider>
            </body>
        </html>
    );
}
